trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Container Registry (ACR) settings
  acrName: 'myacrferfefd'
  acrResourceGroup: 'rg_testing_terraform'
  acrServiceConnection: 'acr-connection'

  # Azure Kubernetes Service (AKS) settings
  aksCluster: 'testcheck'
  aksServiceConnection: 'aks-connection'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push to ACR'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(AcrServiceConnection)'  # Fix casing here
        repository: 'testing'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)

    - task: CopyFiles@2
      displayName: 'Copy Files to: drop'
      inputs:
        SourceFolder: deployment
        Contents: deployment.yaml
        TargetFolder: drop
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: deployment/deployment.yaml
      
          
- stage: DeployToAKS
  displayName: 'Deploy to AKS'
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - checkout: self
    - task: AzureKubernetesService@1
      displayName: 'Deploy to AKS'
      inputs:
        azureSubscriptionEndpoint: '$(AksServiceConnection)'  # Fix casing here
        aksCluster: '$(aksCluster)'
        command: 'kubectl'
        arguments: |
          apply -f $(Build.SourcesDirectory)/k8s/deployment.yaml
