trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'acr-connection'
  sonarServiceConnection: 'sonar-connection'
  aksServiceConnection: 'aks-connection'
  group: sonarlogin

stages:
- stage: Analysis
  jobs:
  - job: AnalysisJob
    displayName: 'Run Analysis'
    steps:
    - checkout: self

    # SonarQube Prepare Analysis Configuration
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'sonar-connection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(ProjectKey)'

- stage: SonarQualityGateCheck
  jobs:
  - job: SonarQualityGateCheckJob
    displayName: 'Sonar Quality Gate Check'
    steps:
    - checkout: self

    # Run SonarQube quality gate check using Bash script
    - script: |
        set -x
        username="$(username)"
        password="$(password)"

        base64AuthInfo=$(echo -n "$username:$password" | base64)

        headers=(
            "Authorization: Basic $base64AuthInfo"
        )

        projectKey="$(ProjectKey)"
        branch="master"
        apiUrl="http://20.15.204.13:9000/api/qualitygates/project_status?projectKey=$projectKey&branch=$branch"

        result=$(curl -s -H "${headers[@]}" "$apiUrl")

        if [[ $(echo "$result" | jq -r .projectStatus.status) == "OK" ]]; then
            echo "Quality Gate Succeeded"
        else
            echo "Quality gate failed"
            exit 1
        fi
