version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Pre Build Phase'
      # Add any pre-build commands here
  build:
    commands:
      - echo 'Build Phase'
      - echo 'Checking out source code'
      # Add your build commands here
      docker build 
  post_build:
    commands:
      - echo 'Post Build Phase'
      # Add any post-build commands here

artifacts:
  files: '**/*'
  discard-paths: yes
